# Pandas

In [1]:
import pandas as pd # pandas 모듈 호출
import numpy as np # numpy 모듈 호출

from pandas import Series, DataFrame

list_data = [1,2,3,4,5]
list_name = ["a","b","c","d","e"]
example_obj = Series(data = list_data, index=list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [2]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [3]:
example_obj.values

array([1, 2, 3, 4, 5])

In [4]:
type(example_obj.values)

numpy.ndarray

In [5]:
example_obj.dtype

dtype('int64')

In [6]:
example_obj.name = "number"
example_obj.index.name = "id"
example_obj

id
a    1
b    2
c    3
d    4
e    5
Name: number, dtype: int64

In [7]:
dict_data = {"a":1, "b":2, "c":3, "d":4, "e":5}
example_obj = Series(dict_data, dtype=np.float32, name="example_data")
example_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [8]:
dict_data_1 = {"a":1, "b":2, "c":3, "d":4, "e":5}
indexes = ["a","b","c","d","e","f","g","h"]
series_obj_1 = Series(dict_data_1, index=indexes)
series_obj_1

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

In [9]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
# 데이터 URL을 변수 data_url에 넣기
df_data = pd.read_csv(data_url, sep='\s+', header = None) # csv 데이터 로드

df = pd.DataFrame(df_data)
df

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2159266923.py:3: SyntaxWarning: invalid escape sequence '\s'
  df_data = pd.read_csv(data_url, sep='\s+', header = None) # csv 데이터 로드

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [10]:
from pandas import Series, DataFrame

raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
'age': [42, 52, 36, 24, 73],
'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}

df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'city'])

df

  first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [11]:
DataFrame(raw_data, columns = ["age", "city"])

   age           city
0   42  San Francisco
1   52      Baltimore
2   36          Miami
3   24        Douglas
4   73         Boston

In [12]:
DataFrame(raw_data,
          columns = ["first_name","last_name","age", "city", "debt"]
         )

  first_name last_name  age           city debt
0      Jason    Miller   42  San Francisco  NaN
1      Molly  Jacobson   52      Baltimore  NaN
2       Tina       Ali   36          Miami  NaN
3       Jake    Milner   24        Douglas  NaN
4        Amy     Cooze   73         Boston  NaN

In [13]:
# 구글 드라이브 mount
from google.colab import drive

drive.mount('/content/gdrive')
colab_path = "/content/gdrive/MyDrive/machinelearning/"

Mounted at /content/gdrive

In [14]:
!conda install --y openpyxl

/bin/bash: line 1: conda: command not found

In [15]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [16]:
# 구글 드라이브 mount
from google.colab import drive

drive.mount('/content/gdrive')
colab_path = "/content/gdrive/MyDrive/Colab Notebooks/machinelearning/"

df = pd.read_excel(colab_path+'excel-comp-data.xlsx')
df

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [17]:
df.head(5)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

In [18]:
df.head(3).T

,0,1,2
account,211829,320563,648336
name,"Kerluke, Koepp and Hilpert",Walter-Trantow,"Bashirian, Kunde and Price"
street,34456 Sean Highway,1311 Alvis Tunnel,62184 Schamberger Underpass Apt. 231
city,New Jaycob,Port Khadijah,New Lilianland
state,Texas,NorthCarolina,Iowa
postal-code,28752,38365,76517
Jan,10000,95000,91000
Feb,62000,45000,120000
Mar,35000,35000,35000

In [19]:
df[["account", "street", "state"]].head(3)

   account                                street          state
0   211829                    34456 Sean Highway          Texas
1   320563                     1311 Alvis Tunnel  NorthCarolina
2   648336  62184 Schamberger Underpass Apt. 231           Iowa

In [20]:
df[:3]

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000

In [21]:
df[["name","street"]][:2]

                         name              street
0  Kerluke, Koepp and Hilpert  34456 Sean Highway
1              Walter-Trantow   1311 Alvis Tunnel

In [22]:
df.index = df["account"]
del df["account"]
df.head()

,name,street,city,state,postal-code,Jan,Feb,Mar
account,,,,,,,,
211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

In [23]:
df.loc[[211829,320563],["name","street"]]

                               name              street
account
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [24]:
df.loc[205217:,["name","street"]]

                                 name                        street
account
205217               Kovacek-Johnston  91971 Cronin Vista Suite 601
209744                 Champlin-Morar              26739 Grant Lock
212303                 Gerhold-Maggio     366 Maggio Grove Apt. 998
214098    Goodwin, Homenick and Jerde     649 Cierra Forks Apt. 078
231907                     Hahn-Moore      18115 Olivine Throughway
242368   Frami, Anderson and Donnelly               182 Bertie Road
268755                    Walsh-Haley          2624 Beatty Parkways
273274                  McDermott PLC         8917 Bergstrom Meadow

In [25]:
df.iloc[:10, :3]

,name,street,city
account,,,
211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob
320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah
648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland
109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh
121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester
132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh
145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton
205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville
209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton
212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras

In [26]:
df_new = df.reset_index()
df_new

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [27]:
df_new.drop(1).head()

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000

In [28]:
df_drop = df_new.drop(1)

In [29]:
df_new.drop(1, inplace=True)

In [30]:
df_new.drop("account", axis=1) # account 열 제거
df_new.drop(["account", "name"], axis=1) # account, name 열 제거

,street,city,state,postal-code,Jan,Feb,Mar
0,34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

## groupby

In [31]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'Kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
            'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
            'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
            'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

df = pd.DataFrame(ipl_data)
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [32]:
df.groupby("Team")["Points"].sum()

Team
Devils    1536
Kings     3097
Riders    3049
Royals    1505
Name: Points, dtype: int64

In [33]:
multi_groupby = df.groupby(["Team", "Year"])["Points"].sum()
multi_groupby

Team    Year
Devils  2014    863
        2015    673
Kings   2014    741
        2015    812
        2016    756
        2017    788
Riders  2014    876
        2015    789
        2016    694
        2017    690
Royals  2014    701
        2015    804
Name: Points, dtype: int64

In [34]:
multi_groupby = df.groupby(["Team", "Year"])["Points"].sum()
multi_groupby.index

MultiIndex([('Devils', 2014),
            ('Devils', 2015),
            ( 'Kings', 2014),
            ( 'Kings', 2015),
            ( 'Kings', 2016),
            ( 'Kings', 2017),
            ('Riders', 2014),
            ('Riders', 2015),
            ('Riders', 2016),
            ('Riders', 2017),
            ('Royals', 2014),
            ('Royals', 2015)],
           names=['Team', 'Year'])

In [35]:
multi_groupby["Devils":"Kings"]

Team    Year
Devils  2014    863
        2015    673
Kings   2014    741
        2015    812
        2016    756
        2017    788
Name: Points, dtype: int64

In [36]:
multi_groupby.unstack()

Year     2014   2015   2016   2017
Team
Devils  863.0  673.0    NaN    NaN
Kings   741.0  812.0  756.0  788.0
Riders  876.0  789.0  694.0  690.0
Royals  701.0  804.0    NaN    NaN

In [37]:
multi_groupby.swaplevel().sort_index()

Year  Team
2014  Devils    863
      Kings     741
      Riders    876
      Royals    701
2015  Devils    673
      Kings     812
      Riders    789
      Royals    804
2016  Kings     756
      Riders    694
2017  Kings     788
      Riders    690
Name: Points, dtype: int64

In [ ]:
grouped = df.groupby("Team")
grouped.get_group("Riders")

In [ ]:
grouped.agg(min)

In [ ]:
grouped.agg(np.mean)

In [ ]:
grouped.transform(max)

In [ ]:
score = lambda x: (x - x.mean()) / x.std()
grouped.transform(score)

In [ ]:
df.groupby('Team').filter(
    lambda x: len(x) >= 3)

In [ ]:
df.groupby('Team').filter(
    lambda x:
    x["Points"].max() > 850)

## merge (join)

In [ ]:
raw_data = {
    'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
    'test_score': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

df_left = pd.DataFrame(raw_data, columns = ['subject_id', 'test_score'])
df_left

In [ ]:
raw_data = {
    'subject_id': ['4', '5', '6', '7', '8'],
    'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
    'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

df_right = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_right

In [ ]:
pd.merge(left=df_left, right=df_right, how="inner", on='subject_id')

In [ ]:
pd.merge(
    df_left, df_right,
    on='subject_id', how='left')

In [ ]:
pd.merge(
    df_left, df_right,
    on='subject_id', how='right')

In [ ]:
pd.merge(df_left, df_right, on='subject_id', how='outer')

In [ ]:
df_left.index = df_left.subject_id
del df_left["subject_id"]
df_right.index = df_right.subject_id
del df_right["subject_id"]

pd.merge(df_left, df_right, on='subject_id', how='inner')

## concatnate

In [ ]:
# 구글 드라이브 mount
from google.colab import drive

drive.mount('/content/gdrive')

In [ ]:
colab_path = "/content/gdrive/MyDrive/Colab Notebooks/machinelearning/"
filenames = [os.path.join(colab_path, filename)
             for filename in os.listdir(colab_path) if "sales" in filename]
print(filenames)

In [ ]:
!pip install --user --upgrade openpyxl

In [ ]:
df_list = [pd.read_excel(filename, engine="openpyxl") for filename in filenames]
for df in df_list:
    print(type(df), len(df))

In [ ]:
df = pd.concat(df_list, axis=0)
print(len(df)) # 384
df.reset_index(drop=True)

In [ ]:
df_1, df_2, df_3 = [pd.read_excel(filename, engine="openpyxl") for
filename in filenames]
df = df_1.append(df_2)
df = df.append(df_3)
df